// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Format a date/time value. Returns empty string if date is empty.
 * @param {Date} dateToFormat
 * @param {string} formatToUse
 * @returns {Promise.<string>}
 */
export async function FormatDateTime(dateToFormat, formatToUse) {
	// BEGIN USER CODE
	return new Promise(function(resolve, reject) {
		var formattedDate;
		if (typeof dateToFormat !== "undefined" && dateToFormat !== null) {
			if (typeof formatToUse !== "undefined" && formatToUse !== null && formatToUse) {
				try {
					formattedDate = mx.parser.formatValue(dateToFormat, "datetime", { datePattern: formatToUse});
					resolve(formattedDate);
				} catch (error) {
					if (error && error.message) {
						reject("FormatDateTime failed: " + error.message);
					} else {
						reject("FormatDateTime failed.");
					}
				}
			} else {
				reject("FormatDateTime: No format specified");
			}
		} else {
			resolve("");
		}
	});
	// END USER CODE
}
