// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package admin.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetInstanceIndex extends CustomJavaAction<java.lang.Long>
{
	public GetInstanceIndex(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger("Instance Index");
		
		long cfInstanceIndex = -1L;
		
		try {
			cfInstanceIndex = Long.parseLong(System.getenv("CF_INSTANCE_INDEX"));
		} catch(SecurityException securityException) {
			logger.warn("GetCFInstanceIndex: Could not access environment variable CF_INSTANCE_INDEX, permission denied. Value of -1 is returned.");
		} catch(NumberFormatException numberFormatException) {
			logger.debug("GetCFInstanceIndex: Could not parse value of environment variable CF_INSTANCE_INDEX as Long. Value of -1 is returned.");
		} catch(NullPointerException nullPointerException) {
			logger.debug("GetCFInstanceIndex: Could not find value for environment variable CF_INSTANCE_INDEX. This could indicate a local deployment is running. Value of -1 is returned.");
		}
		
		return cfInstanceIndex;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetInstanceIndex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
