// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} audioFile
 * @returns {Promise.<void>}
 */
export async function PlaySound(audioFile) {
	// BEGIN USER CODE
	if(!audioFile) {
		return Promise.reject(new Error("Input parameter 'Audio File' is required"));
	}
	if(!audioFile.inheritsFrom("System.FileDocument")) {
		const entity = audioFile.getEntity();
		return Promise.reject(new Error(`Entity ${entity} does not inherit from 'System.FileDocument'`));
	}
	const guid = audioFile.getGuid();
	const changedDate = audioFile.get("changedDate");
	const url = mx.data.getDocumentUrl(guid, changedDate);

	const audioObj = new Audio(url);
	audioObj.play()
	return Promise.resolve();
	// END USER CODE
}
